include theos/makefiles/common.mk

BUNDLE_NAME = WritingALetter
WritingALetter_INSTALL_PATH = /Library/PreferenceBundles
WritingALetter_FRAMEWORKS = UIKit
WritingALetter_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
